### PR TITLE
querying resource extension + minor bug fixes and improvements

### PR DESCRIPTION
**Pull request by rymir75**
- untracked some VS config files and build artefacts
- building and nuget restoring optimizations
- querying resource extension
- new unit tests
- few ignored test are now green
- fixed null reference exception during PUT and PATCH when ETag feature was disabled
- resource extensions serialization improvement
- Antlr upgrade to latest stable
- other second-rate nuget upgraded

### CODE REVIEW

**Comment by rymir75** [comment]
there are small breaking changes in the area of ToPredicate extension method (new parameter) and ScimFilterVisitor (grammar was changed so new method to override, no longer FIELD in parser context)

**Comment by rymir75** [comment]
and of course ScimFilterVisitor ctor which needs now ScimServerConfiguration

**Comment by Cephei** [comment]
Thanks for contributing! I'll read over the changes today and try to get it merged in.

**Comment by Cephei** [comment]
@rymir75 You rock! Your work here is greatly appreciated. Just one question regarding the post build step:
`del $(ProjectDir)..\_build\$(ConfigurationName)\$(ProjectName).*`

What was the intent for this? It's actually giving me issues in the AppVeyor continuous integration. My guess is that the account running the build doesn't have delete rights.

**Comment by rymir75** [comment]
Thanks :)
The intent was that you decided to reference Owin.Scim.Antlr not as project reference but reference to a file and also set copy local to true. In that case Owin.Scim.Antlr wasn't updated in _build\$(Configuration) folder even when I changed it. So when I deleted it in post puild action I was sure that I'm using the latest version (it was copied again). I could also set copy local to false for this reference but then you should change nuspec. If this is a problem with AppVeyor we can always do the above.

**Comment by Cephei** [comment]
Thanks for the info. I'll look into changing CopyLocal to false, but I need to first remember why I used a file reference instead of project.

**Pull request merged**
